name: Backend Tests

on:
  pull_request:
    branches: [main] # se ejecuta cuando alguien abre PR hacia main
    paths:
      - "backend/**"
  push:
    branches:
      - "feature/*"
      - "fix/*"

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Instalar Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3. Instalar pnpm (acción oficial)
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # usa la misma versión que tengas en tu proyecto
          run_install: false

      # 4. Instalar dependencias del backend
      - name: Install dependencies
        working-directory: ./backend
        run: pnpm install

      # 5. Correr tests del backend
      - name: Run backend tests
        working-directory: ./backend
        run: pnpm test
